name: Add four Numbers

on: workflow_dispatch

jobs:
  add:
    runs-on: ubuntu-latest
    steps:
      - name: Add numbers
        run: |
          num1=25
          num2=25
          num3=10
          num4=20
          sum=$((num1 + num2 + num3 + num4))
          echo "Sum is $sum"
