name: Add Two Numbers

on: workflow_dispatch

jobs:
  add:
    runs-on: ubuntu-latest
    steps:
      - name: Add numbers
        run: |
          num1=25
          num2=25
          sum=$((num1 + num2))
          echo "Sum is $sum"
